import { useEffect, useRef, useState, type FormEvent } from 'react';
import type { AppointmentTriageSummary, Hospital, QuestionnaireAnswer, QuestionnaireAssessment, QuestionnaireIntake } from '../../api.ts';
import { IntakeRecommendation } from './IntakeRecommendation.tsx';

type ChatStage = 'intro' | 'chat' | 'result';

interface ChatMessage {
  role: 'ai' | 'patient';
  text: string;
}

export function IntakeChat({
  isAuthenticated,
  hospitals,
  onSignIn,
  onStartIntake,
  onCompleteQuestionnaire,
  onBookAppointment,
}: {
  isAuthenticated: boolean;
  hospitals: Hospital[];
  onSignIn: () => void;
  onStartIntake: (complaint: string) => Promise<QuestionnaireIntake>;
  onCompleteQuestionnaire: (pathwayId: string, answers: QuestionnaireAnswer[]) => Promise<QuestionnaireAssessment>;
  onBookAppointment: (input: { hospitalId?: string; serviceId?: string; triageSummary: AppointmentTriageSummary }) => void;
}) {
  const [stage, setStage] = useState<ChatStage>('intro');
  const [complaint, setComplaint] = useState('');
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [intake, setIntake] = useState<QuestionnaireIntake>();
  const [answers, setAnswers] = useState<QuestionnaireAnswer[]>([]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string>();
  const [conclusion, setConclusion] = useState<{ source: QuestionnaireIntake['source']; fallbackReason?: QuestionnaireIntake['fallbackReason']; assessment: QuestionnaireAssessment }>();
  const messagesRef = useRef<HTMLDivElement>(null);
  const currentQuestion = intake?.questions[answers.length];

  useEffect(() => {
    const node = messagesRef.current;
    if (node) node.scrollTop = node.scrollHeight;
  }, [messages, busy]);

  async function start(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!isAuthenticated) {
      onSignIn();
      return;
    }
    if (complaint.trim().length < 4) return;
    setBusy(true);
    setError(undefined);
    setMessages([]);
    setIntake(undefined);
    setAnswers([]);
    setConclusion(undefined);
    try {
      const nextIntake = await onStartIntake(complaint.trim());
      if (nextIntake.questions.length === 0) throw new Error('The standard intake questionnaire is unavailable. Please try again.');
      setIntake(nextIntake);
      setMessages([{ role: 'ai', text: nextIntake.questions[0].text }]);
      setStage('chat');
    } catch (startError) {
      setError(startError instanceof Error ? startError.message : 'Could not start the conversation.');
    } finally {
      setBusy(false);
    }
  }

  async function submitAnswer(display: string, value: QuestionnaireAnswer['value']) {
    if (!intake || !currentQuestion || busy) return;
    const nextAnswers = [...answers, { questionId: currentQuestion.id, value }];
    setError(undefined);
    if (nextAnswers.length < intake.questions.length) {
      const nextQuestion = intake.questions[nextAnswers.length]!;
      setMessages((current) => [...current, { role: 'patient', text: display }, { role: 'ai', text: nextQuestion.text }]);
      setAnswers(nextAnswers);
      return;
    }
    setMessages((current) => [...current, { role: 'patient', text: display }]);
    setBusy(true);
    try {
      const assessment = await onCompleteQuestionnaire(intake.pathwayId, nextAnswers);
      setAnswers(nextAnswers);
      setConclusion({ source: intake.source, fallbackReason: intake.fallbackReason, assessment });
      setStage('result');
    } catch (answerError) {
      setMessages((current) => current.slice(0, -1));
      setError(answerError instanceof Error ? answerError.message : 'Something went wrong. Please try again.');
    } finally {
      setBusy(false);
    }
  }

  function restart() {
    setStage('intro');
    setComplaint('');
    setMessages([]);
    setIntake(undefined);
    setAnswers([]);
    setError(undefined);
    setConclusion(undefined);
  }

  return (
    <section className="card nv-questionnaire-card" aria-label="AI-assisted intake">
      {stage === 'intro' ? (
        <form className="nv-questionnaire-intro" onSubmit={start}>
          <p className="eyebrow">AI-assisted intake</p>
          <h2>Tell us what you are feeling before you book</h2>
          <p className="muted">Your initial message selects a standard intake questionnaire. The questions and assessment are not generated by AI. This is not a diagnosis.</p>
          <label className="nv-field">
            Main symptom
            <textarea
              value={complaint}
              maxLength={300}
              onChange={(event) => setComplaint(event.target.value)}
              placeholder="For example: I hurt my knee today and it is painful to walk."
            />
          </label>
          <div className="nv-questionnaire-examples">
            {['I have a bad headache', 'My chest feels tight', 'I hurt my ankle today'].map((example) => (
              <button key={example} type="button" onClick={() => setComplaint(example)}>{example}</button>
            ))}
          </div>
          {error ? <p className="nv-error" role="alert">{error}</p> : null}
          <button className="primary-btn" type="submit" disabled={busy || complaint.trim().length < 4}>
            {busy ? 'Starting…' : isAuthenticated ? 'Start assessment' : 'Sign in to start'}
          </button>
        </form>
      ) : null}

      {stage === 'chat' ? (
        <div className="nv-chat">
          <div className="nv-chat-messages" ref={messagesRef} aria-live="polite">
            {messages.map((message, index) => (
              <div key={index} className={`nv-chat-bubble ${message.role}`}>{message.text}</div>
            ))}
              {busy ? <div className="nv-chat-bubble ai nv-chat-typing">Assessing…</div> : null}
            </div>
            {currentQuestion && !busy ? (
              <div className="nv-chat-reply">
                {currentQuestion.type === 'yes-no' ? (
                  <div className="nv-questionnaire-options">
                    <button type="button" className="nv-questionnaire-option" onClick={() => void submitAnswer('Yes', true)}>Yes</button>
                    <button type="button" className="nv-questionnaire-option" onClick={() => void submitAnswer('No', false)}>No</button>
                  </div>
                ) : null}
                {currentQuestion.type === 'single' ? (
                  <div className="nv-questionnaire-options">
                    {currentQuestion.options?.map((option) => (
                      <button key={option.id} type="button" className="nv-questionnaire-option" onClick={() => void submitAnswer(option.label, option.value)}>
                        {option.label}
                    </button>
                  ))}
                </div>
              ) : null}
              {currentQuestion.type === 'scale' ? (
                <div className="nv-chat-scale">
                  <span className="muted small">0 = none · 10 = worst</span>
                  <div className="nv-chat-scale-options">
                    {Array.from({ length: 11 }, (_, value) => (
                      <button key={value} type="button" className="nv-chat-scale-chip" onClick={() => void submitAnswer(`${value}/10`, value)}>{value}</button>
                    ))}
                  </div>
                </div>
              ) : null}
            </div>
          ) : null}
          {error ? <p className="nv-error" role="alert">{error}</p> : null}
          <p className="muted small">AI is used only to select this standard questionnaire. A nurse reviews everything before you are placed in a queue.</p>
        </div>
      ) : null}

      {stage === 'result' && conclusion ? (
        <IntakeRecommendation
          hospitals={hospitals}
          pathwayName={conclusion.assessment.pathwayName}
          source={conclusion.source}
          fallbackReason={conclusion.fallbackReason}
          urgency={conclusion.assessment.urgency}
          department={conclusion.assessment.department}
          reason={conclusion.assessment.summary}
          redFlags={conclusion.assessment.redFlags}
          onBookAppointment={onBookAppointment}
          onRestart={restart}
        />
      ) : null}
    </section>
  );
}
